---
- name: Remove snap packages
  community.general.snap:
    name: "{{ item }}"
    state: absent
  become: true
  loop: "{{ snap_remove_packages }}"

- name: Install snap packages
  community.general.snap:
    name: "{{ item }}"
    classic: true
  become: true
  loop: "{{ snap_packages }}"
