---
# OS suffix mapping from Ansible facts to Rust target triplets
# Architecture from ansible_architecture is already correct (x86_64, aarch64, etc.)
rust_os_suffix_map:
  Linux: unknown-linux-gnu
  Darwin: apple-darwin
  FreeBSD: unknown-freebsd
  OpenBSD: unknown-openbsd
  NetBSD: unknown-netbsd
  Windows: pc-windows-msvc

# Determine if we should build locally (when using SSH connection)
build_locally: "{{ ansible_connection == 'ssh' }}"

# Rust cross-compilation target
rust_target: "{{ ansible_architecture }}-{{ rust_os_suffix_map[ansible_system] | default('unsupported') }}"

# Build cache subdirectory name
cargo_cache_subdir: "ansible-cargo-builds"
