{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.services.usbguard;
  inherit (config.dotfiles.desktop.usbguard) staticRules;

  ruleFolder = "/etc/usbguard/rules.d/";

  daemonConf = pkgs.writeText "usbguard-daemon-conf" ''
    # generated by nix/modules/gnome/usbguard.nix
    RuleFile=${cfg.ruleFile}
    RuleFolder=${ruleFolder}
    ImplicitPolicyTarget=${cfg.implicitPolicyTarget}
    PresentDevicePolicy=${cfg.presentDevicePolicy}
    PresentControllerPolicy=${cfg.presentControllerPolicy}
    InsertedDevicePolicy=${cfg.insertedDevicePolicy}
    RestoreControllerDeviceState=${lib.boolToString cfg.restoreControllerDeviceState}
    DeviceManagerBackend=uevent
    IPCAllowedUsers=${lib.concatStringsSep " " cfg.IPCAllowedUsers}
    IPCAllowedGroups=${lib.concatStringsSep " " cfg.IPCAllowedGroups}
    IPCAccessControlFiles=/var/lib/usbguard/IPCAccessControl.d/
    DeviceRulesWithPort=${lib.boolToString cfg.deviceRulesWithPort}
    AuditFilePath=/dev/null
  '';
in {
  config = lib.mkMerge [
    {
      assertions = [
        {
          assertion = !(cfg.enable && cfg.rules != null);
          message = ''
            modules/gnome/usbguard.nix requires services.usbguard.rules to remain unset
            so usbguard can keep a writable RuleFile alongside declarative RuleFolder entries.
          '';
        }
      ];
    }

    (lib.mkIf cfg.enable {
      environment.etc =
        lib.mapAttrs' (
          name: text:
            lib.nameValuePair "usbguard/rules.d/${name}" {inherit text;}
        )
        staticRules;

      systemd.services.usbguard.serviceConfig.ExecStart =
        lib.mkForce "${cfg.package}/bin/usbguard-daemon -P -k -c ${daemonConf}";
    })
  ];
}
