---
- name: Set up facts
  hosts: all
  gather_facts: true
  run_once: true
  tags: ["always"]
  tasks:
    - name: Set initial facts
      ansible.builtin.set_fact:
        os_distribution: "{{ ansible_distribution | lower }}"
        os_type: "{{ ansible_system | lower }}"
        os_family: "{{ ansible_os_family | lower }}"

    - name: Add host to OS group
      ansible.builtin.add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ os_type }}"

    - name: Add host to OS distribution group
      ansible.builtin.add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ os_distribution }}"

    - name: Add host to OS family group
      ansible.builtin.add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ os_family }}_family"

- name: Debug
  hosts: all
  tags: ["debug"]
  tasks:
    - name: Print available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print groups for verification
      ansible.builtin.debug:
        msg: "{{ group_names }}"

- name: Common setup (debian-based)
  hosts: debian_family
  tags: ["common", "system"]
  roles:
    - role: apt
      tags: ["apt"]
    - role: pipx
      tags: ["pipx"]

- name: Debian setup
  hosts: debian
  tags: ["debian", "system"]
  roles:
    - role: apt

- name: Common setup
  hosts: all
  tags: ["common", "system"]
  roles:
    - role: user
      tags: ["user"]
    - role: zsh
      tags: ["zsh"]
    - role: neovim
      tags: ["neovim"]
    - role: cargo
      tags: ["cargo"]
    - role: git
      tags: ["git"]
    - role: go
      tags: ["go"]
    - role: luarocks
      tags: ["luarocks"]

- name: Set up Linux desktop
  hosts: debian_family:&desktop
  tags: ["debian_family", "desktop", "system"]
  roles:
    - role: apt
      tags: ["apt"]
    - role: google-chrome
      tags: ["browser"]
    - role: pipewire
      tags: ["audio"]

- name: Set up Ubuntu workstation
  hosts: ubuntu:&desktop
  tags: ["ubuntu", "system"]
  roles:
    - role: snap
      tags: ["snap"]

- name: Set up local workstation (macos)
  hosts: darwin
  tags: ["macos", "system"]
  roles:
    - role: brew
      tags: ["brew"]

- name: Set up common tools (all desktop systems)
  hosts: desktop
  tags: ["common", "desktop"]
  roles:
    - role: fonts
      tags: ["fonts"]

- name: Install work things
  hosts: work
  tags: ["work"]
  roles:
    - role: cloud_sdks
      tags: ["cloud"]
    - role: work_packages
      tags: ["packages"]

- name: Install home things
  hosts: home
  tags: ["home"]
  roles:
    - role: terraform
      tags: ["terraform"]
