- name: Set up OS facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Set os_family fact
      set_fact:
        os_family: "{{ ansible_distribution | lower }}"

    - name: Get OS type
      shell: uname -s
      register: uname_s

    - name: Set os_type fact
      set_fact:
        os_type: "{{ uname_s.stdout | lower }}"

    - name: Map Ubuntu to Debian
      set_fact:
        os_family: "debian"
      when: os_family == "ubuntu"

    - name: Map `macosx` to `macos`
      set_fact:
        os_family: "macos"
      when: os_family == "macosx"

- name: Add host to OS group
  hosts: all
  tasks:
    - name: Add host to OS group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ os_type }}"

- name: Add host to home group if not a work machine
  hosts: all:!work
  tasks:
    - name: Add host to home group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: home

- name: Print groups
  hosts: all
  tasks:
    - name: Print
      debug:
        msg: "{{ group_names }}"

- name: Set up local workstation (all)
  hosts: all
  roles:
    - role: user
    - role: git
    - role: go
    - role: cargo

- name: Set up local workstation (debian)
  hosts: linux
  roles:
    - role: apt
    - role: google-chrome
    - role: snap
    - role: pipewire

- name: Set up local workstation (macos)
  hosts: macos
  roles:
    - role: brew

- name: Install work things
  hosts: work
  roles:
    - role: cloud-sdks
    - role: work-packages

- name: Install home things
  hosts: home
  roles:
    - role: terraform
