- name: Set up local workstation (all)
  hosts: all
  roles:
    - role: git
      tags:
        - git
        - all
    - role: go
      tags:
        - go
        - all
    - role: apt
      tags:
        - apt
        - all
    - role: google-chrome
      tags:
        - google-chrome
        - all
    - role: snap
      tags:
        - snap
        - all
    - role: pipewire
      tags:
        - pipewire
        - all
    - role: user
      tags:
        - user
        - all
    - role: cargo
      tags:
        - cargo
        - all
- name: Install work things
  hosts: work
  roles:
    - role: cloud-sdks
      tags:
        - cloud-sdks
        - work
    - role: work-packages
      tags:
        - work-packages
        - work
