- name: Create users
  user:
    append: true
    update_password: on_create

    # per user
    comment: "{{ item.comment }}"
    groups: "{{ item.groups }}"
    name: "{{ item.name }}"
    shell: "{{ item.shell}}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ users }}"

- name: Copy a new zshrc
  copy:
    src: templates/zshrc
    dest: "~/.zshrc"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0664"
    backup: yes
  loop: "{{ users }}"

- name: Copy a new zshrc.local
  copy:
    src: templates/zshrc.local
    dest: "~/.zshrc.local"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0664"
    backup: yes
  loop: "{{ users }}"

- name: Set npm path
  command:
    cmd: npm config set prefix ~/.npm
  become: no

- name: avoid annoying message when running docker
  copy:
    content: ""
    dest: /etc/containers/nodocker
    force: false
    group: root
    owner: root
    mode: 0644
  become: no

- name: Clone monaspace repo
  git:
    repo: "https://github.com/githubnext/monaspace.git"
    dest: "~/dev/random/monaspace"
    update: yes
  become: no

- name: Ensure font directory exists
  file:
    path: "~/.local/share/fonts"
    state: directory
  become: no

- name: Install monaspace fonts
  command:
    chdir: "~/dev/random/monaspace"
    cmd: "util/install_linux.sh"
  become: no
