- name: Create users
  user:
    append: true
    update_password: on_create

    # per user
    comment: "{{ item.comment }}"
    groups: "{{ usergroups[os_family][item.user_type] }}"
    name: "{{ item.name }}"
    shell: "{{ item.shell}}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ users }}"

  vars:
    usergroups:
      macos:
        admin: [admin]
        regular: []
      debian:
        admin: [sudo, kvm]
        regular: []

- name: Define zplug path
  set_fact:
    zplug_zshrc_path: "~/dev/random/zplug"

- name: Install zplug
  git:
    repo: https://github.com/zplug/zplug
    dest: "{{ zplug_zshrc_path }}"
    update: yes

# Do the copying above in a loop
- name: Copy zsh files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0664"
  loop:
    - { src: "templates/zshrc", dest: "~/.zshrc" }
    - { src: "templates/zshrc.local", dest: "~/.zshrc.local" }
    - { src: "templates/zshenv", dest: "~/.zshenv" }

- name: Make empty ~/.zsh-functions directory
  file:
    path: ~/.zsh-functions
    state: directory

- name: Set npm path
  command:
    cmd: npm config set prefix ~/.npm
  become: no

- name: avoid annoying message when running docker
  copy:
    content: ""
    dest: /etc/containers/nodocker
    force: false
    group: root
    owner: root
    mode: 0644
  become: no
  when: os_family == "debian"

- name: Clone monaspace repo
  git:
    repo: "https://github.com/githubnext/monaspace.git"
    dest: "~/dev/random/monaspace"
    update: yes
  become: no

- name: Ensure font directory exists
  file:
    path: "~/.local/share/fonts"
    state: directory
  become: no

- name: Install monaspace fonts
  command:
    chdir: "~/dev/random/monaspace"
    cmd: "util/install_{{ os_family }}.sh"
  become: no

  vars:
    os_type: "{{ ansible_distribution }}"
