---
- name: Create users
  ansible.builtin.user:
    append: true
    update_password: on_create

    # per user
    comment: "{{ item.comment }}"
    groups: "{{ usergroups[os_family][item.user_type] }}"
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
  become: true
  loop: "{{ user_list }}"

  vars:
    usergroups:
      macos:
        admin: [admin]
        regular: []
      debian:
        admin: [sudo, kvm]
        regular: []

- name: Create zsh files
  block:
    - name: Ensure zsh config directory exists
      ansible.builtin.file:
        path: "~/.config/zsh"
        state: directory
        mode: "0755"

    - name: Copy zsh files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        directory_mode: "0755"
        mode: "0664"
      loop:
        - { src: "templates/zsh/functions/", dest: "~/.config/zsh/functions/" }
        - { src: "templates/zsh/plugins/", dest: "~/.config/zsh/plugins/" }
        - { src: "templates/zsh/zsh_plugins.txt", dest: "~/.config/zsh/zsh_plugins.txt" }
        - { src: "templates/zsh/zshenv", dest: "~/.zshenv" }
        - { src: "templates/zsh/zshrc", dest: "~/.config/zsh/.zshrc" }
        - { src: "templates/zsh/zstyles-post.zsh", dest: "~/.config/zsh/zstyles-post.zsh" }
        - { src: "templates/zsh/zstyles.zsh", dest: "~/.config/zsh/zstyles.zsh" }

- name: Neovim files
  block:
    - name: Ensure neovim config directory exists
      ansible.builtin.file:
        path: ~/.config/nvim
        state: directory
        mode: "0755"

    - name: Copy neovim files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        directory_mode: "0755"
        mode: "0664"
      loop:
        - { src: "templates/nvim/", dest: "~/.config/nvim/" }

- name: Starship files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    directory_mode: "0755"
    mode: "0664"
  loop:
    - { src: "templates/starship/", dest: "~/.config/" }

# This prevents a "Last login" message from appearing when you open a new terminal
- name: Create a hushlogin file
  ansible.builtin.copy:
    content: ""
    dest: "~/.hushlogin"
    force: false
    mode: "0644"

- name: Set npm path
  ansible.builtin.command:
    cmd: npm config set prefix ~/.npm
    creates: "~/.npmrc"
  become: false

- name: Avoid annoying message when running docker
  ansible.builtin.copy:
    content: ""
    dest: /etc/containers/nodocker
    force: false
    group: root
    owner: root
    mode: "0644"
  become: true
  when: os_family == "debian"
