- name: Create users
  user:
    append: true
    update_password: on_create

    # per user
    comment: "{{ item.comment }}"
    groups: "{{ usergroups[os_family][item.user_type] }}"
    name: "{{ item.name }}"
    shell: "{{ item.shell}}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ users }}"

  vars:
    usergroups:
      macos:
        admin: [admin]
        regular: []
      debian:
        admin: [sudo, kvm]
        regular: []

# Do the copying above in a loop
- name: zsh files
  block:
  - name: Ensure zsh config directory exists
    file:
      path: "~/.config/zsh"
      state: directory

  - name: Copy zsh files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      directory_mode: "0755"
      mode: "0664"
    loop:
      - { src: "templates/zshenv", dest: "~/.zshenv" }
      - { src: "templates/zsh-functions/", dest: "~/.config/zsh/zsh-functions/" }
      - { src: "templates/zsh_plugins.txt", dest: "~/.config/zsh/zsh_plugins.txt" }
      - { src: "templates/zshrc.d/", dest: "~/.config/zsh/zshrc.d/" }
      - { src: "templates/zshrc", dest: "~/.config/zsh/.zshrc" }
      - { src: "templates/zstyles.zsh", dest: "~/.config/zsh/zstyles.zsh" }

# This prevents a "Last login" message from appearing when you open a new terminal
- name: Create a hushlogin file
  copy:
    content: ""
    dest: "~/.hushlogin"
    force: false
    mode: 0644

- name: Set npm path
  command:
    cmd: npm config set prefix ~/.npm
  become: no

- name: avoid annoying message when running docker
  copy:
    content: ""
    dest: /etc/containers/nodocker
    force: false
    group: root
    owner: root
    mode: 0644
  become: yes
  when: os_family == "debian"
