---
- name: Install go packages (work)
  ansible.builtin.command:
    cmd: go install '{{ item }}'
    creates: "{{ ansible_env.HOME }}/go/bin/{{ item | basename | regex_replace('@.*$', '') }}"
  loop:
    - github.com/derailed/k9s@latest
    - github.com/google/go-containerregistry/cmd/crane@latest
    - github.com/jesseduffield/lazygit@latest
    - github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
    - github.com/open-policy-agent/conftest@latest
