- name: Upgrade apt packages
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
  become: true
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: true
    state: latest
    cache_valid_time: 3600
  become: true
  become_user: root
  become_method: sudo
  loop: "{{ packages }}"

- name: Remove apt packages
  apt:
    name: "{{ item }}"
    update_cache: false
    state: absent
  become: true
  become_user: root
  become_method: sudo
  loop: "{{ remove_packages if remove_packages is iterable else [] }}"
