---
# Build the mise tools dictionary from cargo packages
- name: Build mise tools dictionary for Cargo
  ansible.builtin.set_fact:
    cargo_mise_tools: "{{ dict(['cargo:'] | product(cargo_packages) | map('join') | zip_longest([], fillvalue='latest')) }}"

- name: Configure mise for Cargo tools
  ansible.builtin.include_role:
    name: mise_config
  vars:
    mise_config_name: cargo
    mise_priority: "15"
    mise_tools: "{{ cargo_mise_tools }}"
