---
- name: Setup Rust components
  ansible.builtin.include_tasks: setup_rust.yml

# Choose build strategy based on connection type
- name: Build Cargo packages for local system
  ansible.builtin.include_tasks: build_local.yml
  when: not build_locally

- name: Build Cargo packages for target system (cross-compilation)
  ansible.builtin.include_tasks: build_target.yml
  when: build_locally
