---
# Download and run rustup
- name: Install Rust
  block:
    - name: Create temporary file for rustup installer
      ansible.builtin.tempfile:
        state: file
        prefix: rustup_
        suffix: .sh
      register: rustup_tmp

    - name: Download rustup installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: "{{ rustup_tmp.path }}"
        mode: '0755'

    - name: Install Rust
      ansible.builtin.command:
        cmd: "{{ rustup_tmp.path }} -y --no-modify-path"
        creates: ~/.cargo/bin/rustup
      register: rustup

  always:
    - name: Clean up temp file
      ansible.builtin.file:
        path: "{{ rustup_tmp.path }}"
        state: absent
      when: rustup_tmp.path is defined

- name: Update rust
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - ~/.cargo/bin/rustup self update
    - ~/.cargo/bin/rustup update
  when: not rustup.changed

- name: Install Rust components
  ansible.builtin.command:
    cmd: ~/.cargo/bin/rustup component add {{ item }}
  loop:
    - rustfmt
    - clippy
    - rust-analysis
    - rust-src
  when: rustup.changed

- name: Install Cargo packages
  community.general.cargo:
    locked: true
    state: latest
    name:
      - bat
      - bottom
      - du-dust
      - exa
      - fd-find
      - git-delta
      - ripgrep
      - starship
      - tokei
      - zoxide
