# curl and run rustup
- name: Install Rust
  command:
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
    creates: ~/.cargo/bin/rustup
    chdir: ~
  register: rustup

- name: Update rust
  command:
    cmd: "{{ item }}"
  loop:
    - ~/.cargo/bin/rustup self update
    - ~/.cargo/bin/rustup update
  when: not rustup.changed

- name: Install Rust components
  command:
    cmd: ~/.cargo/bin/rustup component add {{ item }}
  loop:
    - rustfmt
    - clippy
    - rust-analysis
    - rust-src
  when: rustup.changed

- name: Install Cargo packages
  community.general.cargo:
    locked: yes
    state: latest
    name:
      - bat
      - bottom
      - du-dust
      - exa
      - fd-find
      - git-delta
      - ripgrep
      - starship
      - tokei
      - zoxide
