---
- name: Add gcloud sdk
  become: true

  block:
    - name: Gcloud gpg key
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/keyrings/google-cloud.asc
        mode: '0644'

    - name: Gcloud apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/google-cloud.asc] https://packages.cloud.google.com/apt cloud-sdk main"
        state: present

    - name: Install gcloud sdk
      ansible.builtin.apt:
        pkg:
          - google-cloud-cli
          - google-cloud-sdk-gke-gcloud-auth-plugin
- name: Add azure sdk
  become: true

  block:
    - name: Azure gpg key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft.asc
        mode: '0644'

    - name: Az apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/azure-cli/ jammy main"
        state: present

    - name: Install az sdk
      ansible.builtin.apt:
        name: azure-cli

- name: Make sure apt aws cli is not installed
  ansible.builtin.apt:
    name: awscli
    state: absent
  become: true
