---
apt_package_upgrade: true

# Base apt packages (installed everywhere)
apt_packages_base:
  - apt
  - black
  - btop
  - build-essential
  - ccache
  - cmake
  - curl
  - htop
  - httpie
  - neovim
  - npm
  - pandoc
  - pipx
  - podman
  - podman-docker
  - pre-commit
  - pycodestyle
  - python3-pip
  - python3-venv
  - rsync
  - ruby
  - watchman
  - wget
  - zsh

# Linux-specific packages (set in group_vars/linux)
apt_packages_linux: []

# Desktop-specific packages (set in group_vars/desktop)
apt_packages_desktop: []

# Server-specific packages (set in group_vars/server)
apt_packages_server: []

# Home-specific packages (set in group_vars/home)
apt_packages_home: []

# Combined package list based on groups and platform
apt_packages: "{{ apt_packages_base + apt_packages_desktop + apt_packages_server + apt_packages_linux + apt_packages_home }}"

apt_remove_packages: []

apt_repositories: {}

apt_state: "{{ 'latest' if apt_package_upgrade else 'present' }}"

apt_update_cache: true
