---
- name: Skip when not on MacOS
  ansible.builtin.meta: end_role
  when: "'darwin' not in group_names"

- name: Manage homebrew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_taps }}"

- name: Remove homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: absent
  loop: "{{ brew_remove_packages }}"

- name: Manage homebrew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: "{{ brew_state }}"
