# vim: set expandtab ts=2 sw=2:
# use emacs keybindings
bindkey -e

# Environment variables
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
export LC_ALL="en_GB.UTF-8"
export LANG="en_GB.UTF-8"
export TZ="Europe/London"

export QUILT_PATCHES=debian/patches
export BAT_THEME_LIGHT="Catppuccin Latte"
export BAT_THEME_DARK="Catppuccin Mocha"

# This is where the `pipx` Ansible role installs binaries. The default
# `~/.local/bin/` is owned by Ansible and will be cleared out on each run, so
# `pipx` needs to install elsewhere.
export PIPX_BIN_DIR="${HOME}/.local/pipx/bin"

if [[ -f "${ZDOTDIR}/zstyles.zsh" ]]; then
   source "${ZDOTDIR}/zstyles.zsh"
fi

# Plugin management with antidote
if [[ ! -d "${ZDOTDIR}/.antidote" ]]; then
  git clone --depth 1 https://github.com/mattmc3/antidote "${ZDOTDIR}/.antidote"
fi

fpath+=("${ZDOTDIR}/.antidote/functions")

{
   pushd "${ZDOTDIR}" >/dev/null

   if [[ ! "zsh_plugins.zsh" -nt "zsh_plugins.txt" ]] || [[ ! "zsh_plugins.zsh" -nt "plugins/" ]]; then
         if [[ ! -f "zsh_plugins.txt" ]]; then
            touch "zsh_plugins.txt"
         fi

         autoload -Uz antidote

         antidote bundle < "zsh_plugins.txt" >| "zsh_plugins.zsh"
   fi

   popd >/dev/null
}

source "${ZDOTDIR}/zsh_plugins.zsh"

if [[ -f "${ZDOTDIR}/zstyles-post.zsh" ]]; then
   source "${ZDOTDIR}/zstyles-post.zsh"
fi

eval "$(starship init zsh)"

zmodload zsh/datetime
