---
dependencies:
  - role: apt
    vars:
      apt_packages:
        - libspa-0.2-bluetooth
        - libspa-0.2-jack
        - libspa-0.2-modules
        - pipewire
        - pipewire-pulse
        - wireplumber
