- name: Install go packages (all)
  command:
    cmd: go install '{{ item }}'
  loop:
    - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - github.com/muesli/deckmaster@latest
    - github.com/muesli/duf@latest
    - github.com/rs/curlie@latest
