- name: Add terraform
  block:
    - name: gpg key
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/keyrings/hashicorp.asc

    - name: apt source
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: install
      apt:
        pkg:
          - terraform
  become: true
  become_user: root
  become_method: sudo
  when: os_family == 'debian'

- name: Add terraform (MacOS)
  block:
    - name: Tap
      community.general.homebrew_tap:
        name: hashicorp/tap

    - name: Install
      community.general.homebrew:
        name: terraform
  when: os_family == 'macos'
