---
# renovate: datasource=golang-version depName=golang
go_version: "1.23.5"

# Base Go packages (installed everywhere)
go_packages_base:
  - github.com/jesseduffield/lazygit
  - github.com/junegunn/fzf
  - github.com/mr-karan/doggo/cmd/doggo
  - github.com/muesli/duf
  - github.com/rs/curlie

# Linux-specific packages (set in group_vars/linux)
go_packages_linux: []

# Desktop-specific packages (set in group_vars/desktop)
go_packages_desktop: []

# Server-specific packages (set in group_vars/server)
go_packages_server: []

# Combined package list based on groups and platform
go_packages: "{{ go_packages_base + go_packages_desktop + go_packages_server + go_packages_linux }}"
