---
# Base packages
brew_packages:
  - btop
  - diffutils
  - eza
  - gnu-sed
  - gnu-tar
  - grep
  - keychain
  - neovim
  - openssh
  - pipx
  - pre-commit
  - presenterm
  - wdiff
brew_taps: []
brew_state: latest
