skip_global_compinit=1

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-${HOME}/.cache}

export ZDOTDIR=${ZDOTDIR:-${XDG_CONFIG_HOME}/zsh}

mkdir -p ${XDG_CONFIG_HOME} ${XDG_DATA_HOME} ${XDG_CACHE_HOME} ${ZDOTDIR}

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath
