- name: Add gcloud sdk
  block:
    - name: gcloud gpg key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/keyrings/google-cloud.asc

    - name: gcloud apt source
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/google-cloud.asc] https://packages.cloud.google.com/apt cloud-sdk main"
        state: present

    - name: install gcloud sdk
      apt:
        pkg:
          - google-cloud-cli
          - google-cloud-sdk-gke-gcloud-auth-plugin
  become: true
  become_user: root
  become_method: sudo

- name: Add azure sdk
  block:
    - name: azure gpg key
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft.asc

    - name: az apt source
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/azure-cli/ jammy main"
        state: present

    - name: install az sdk
      apt:
        name: azure-cli
  become: true
  become_user: root
  become_method: sudo

- name: Make sure apt aws cli is not installed
  apt:
    name: awscli
    state: absent
  become: true
  become_user: root
  become_method: sudo
