---
# Architecture mapping from Ansible facts to Go build system
go_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
  i386: "386"

# OS mapping from Ansible facts to Go build system
go_os_map:
  Linux: linux
  Darwin: darwin
  FreeBSD: freebsd
  OpenBSD: openbsd
  NetBSD: netbsd
  Windows: windows

# Determine if we should build locally (when using SSH connection)
build_locally: "{{ ansible_connection == 'ssh' }}"

# Cross-compilation environment variables
go_cross_env:
  GOOS: "{{ go_os_map[ansible_system] | default(ansible_system | lower) }}"
  GOARCH: "{{ go_arch_map[ansible_architecture] | default('unsupported') }}"

# Build cache subdirectory name
go_cache_subdir: "ansible-go-builds"
