- include_tasks:
    file: roles/apt/tasks/main.yml

- name: Install go packages (work)
  command:
    cmd: go install '{{ item }}'
  loop:
    - github.com/derailed/k9s@latest
    - github.com/google/go-containerregistry/cmd/crane@latest
    - github.com/jesseduffield/lazygit@latest
    - github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
    - github.com/open-policy-agent/conftest@latest
