---
user_config_dir: "{{ lookup('env', 'XDG_CONFIG_HOME', default='~/.config') }}"
user_repos_dir: "{{ lookup('env', 'XDG_CACHE_HOME', default='~/.cache') }}"

user_list:
  - name: laney
    comment: Iain Lane
    user_type: admin
    shell: /bin/zsh
