---
- name: Ensure Ansible state directory exists
  ansible.builtin.file:
    path: "{{ fonts_state_dir }}"
    state: directory
    mode: "0755"
  become: false
  register: state_dir

- name: Load state file
  ansible.builtin.slurp:
    path: "{{ fonts_state_file }}"
  register: state_content
  ignore_errors: true

- name: Set state fact
  ansible.builtin.set_fact:
    state: "{{ (state_content.content | b64decode | from_json) if state_content.content is defined else {'fonts': {}} }}"

- name: Set state fact
  ansible.builtin.set_fact:
    fonts_state: "{{ state.fonts }}"

- name: Install Monaspace fonts
  block:
    - name: Get latest Monaspace release
      ansible.builtin.uri:
        url: https://api.github.com/repos/githubnext/monaspace/tags
        body_format: json
      register: monaspace_release

    - name: Set Monaspace release facts
      ansible.builtin.set_fact:
        monaspace_tag: "{{ monaspace_release.json[0].name }}"
        monaspace_url: "{{ monaspace_release.json[0].tarball_url }}"

    - name: Install Monaspace if not already installed
      when: fonts_state.monaspace is not defined or fonts_state.monaspace != monaspace_tag
      block:
        - name: Include font installation tasks
          ansible.builtin.include_tasks: install_font.yml
          vars:
            font_name: monaspace
            version: "{{ monaspace_tag }}"
            download_url: "{{ monaspace_url }}"
            extract_opts: ["--strip-components=1"]
            script: "{{ (os_family == 'linux') | ternary('./util/install_linux.sh', './util/install_macos.sh') }}"

- name: Install Cascadia Code font if not already installed
  block:
    - name: Get latest Cascadia Code release
      ansible.builtin.uri:
        url: https://api.github.com/repos/microsoft/cascadia-code/releases/latest
        body_format: json
      register: cascadia_release

    - name: Set Cascadia release facts
      ansible.builtin.set_fact:
        cascadia_tag: "{{ cascadia_release.json.tag_name }}"
        cascadia_url: "{{ cascadia_release.json.assets[0].browser_download_url }}"

    - name: Install Cascadia Code if not already installed
      when: fonts_state.cascadia is not defined or fonts_state.cascadia != cascadia_tag
      ansible.builtin.include_tasks: install_font.yml
      vars:
        font_name: cascadia
        version: "{{ cascadia_tag }}"
        download_url: "{{ cascadia_url }}"
        font_paths:
          - "ttf/*.ttf"
          - "ttf/static/*.ttf"

- name: Install Nerd Fonts
  block:
    - name: Get latest Nerd Fonts release
      ansible.builtin.uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        body_format: json
      register: nerdfonts_release

    - name: Set Nerd Fonts release facts
      ansible.builtin.set_fact:
        nerdfonts_tag: "{{ nerdfonts_release.json.tag_name }}"
        nerdfonts_assets: "{{ nerdfonts_release.json.assets | map(attribute='browser_download_url') | list }}"

    - name: Install each Nerd Font
      loop: "{{ fonts_nerd_fonts }}"
      when: fonts_state[font ~ '_nf'] is not defined or fonts_state[font ~ '_nf'] != nerdfonts_tag
      ansible.builtin.include_tasks: install_font.yml
      loop_control:
        loop_var: font
      vars:
        font_name: "{{ font }}_nf"
        version: "{{ nerdfonts_tag }}"
        download_url: "{{ nerdfonts_assets | select('search', font + '.tar.xz$') | first }}"
        font_paths:
          - "*.ttf"
